FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow boto3

WORKDIR /mlflow

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////mlflow/mlflow.db", \
     "--default-artifact-root", "s3://mlflow/", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--allowed-hosts", "mlflow:5000,localhost:5000,localhost:5001,localhost"]
